<?php

namespace DoctrineProxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mpost extends \Mpost implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'acceptedPets' => [parent::class, 'acceptedPets', null, 16],
        "\0".parent::class."\0".'booked' => [parent::class, 'booked', null, 16],
        "\0".parent::class."\0".'datein' => [parent::class, 'datein', null, 16],
        "\0".parent::class."\0".'dateout' => [parent::class, 'dateout', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'house' => [parent::class, 'house', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'moreinfo' => [parent::class, 'moreinfo', null, 16],
        "\0".parent::class."\0".'numreport' => [parent::class, 'numreport', null, 16],
        "\0".parent::class."\0".'offers' => [parent::class, 'offers', null, 16],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null, 16],
        "\0".parent::class."\0".'reportreceived' => [parent::class, 'reportreceived', null, 16],
        "\0".parent::class."\0".'seller' => [parent::class, 'seller', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        'acceptedPets' => [parent::class, 'acceptedPets', null, 16],
        'booked' => [parent::class, 'booked', null, 16],
        'datein' => [parent::class, 'datein', null, 16],
        'dateout' => [parent::class, 'dateout', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'house' => [parent::class, 'house', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'moreinfo' => [parent::class, 'moreinfo', null, 16],
        'numreport' => [parent::class, 'numreport', null, 16],
        'offers' => [parent::class, 'offers', null, 16],
        'price' => [parent::class, 'price', null, 16],
        'reportreceived' => [parent::class, 'reportreceived', null, 16],
        'seller' => [parent::class, 'seller', null, 16],
        'title' => [parent::class, 'title', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
