<?php

namespace DoctrineProxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Moffer extends \Moffer implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'client' => [parent::class, 'client', null, 16],
        "\0".parent::class."\0".'dateofferin' => [parent::class, 'dateofferin', null, 16],
        "\0".parent::class."\0".'dateofferout' => [parent::class, 'dateofferout', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'post' => [parent::class, 'post', null, 16],
        "\0".parent::class."\0".'requiredPets' => [parent::class, 'requiredPets', null, 16],
        "\0".parent::class."\0".'review' => [parent::class, 'review', null, 16],
        "\0".parent::class."\0".'state' => [parent::class, 'state', null, 16],
        'client' => [parent::class, 'client', null, 16],
        'dateofferin' => [parent::class, 'dateofferin', null, 16],
        'dateofferout' => [parent::class, 'dateofferout', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'post' => [parent::class, 'post', null, 16],
        'requiredPets' => [parent::class, 'requiredPets', null, 16],
        'review' => [parent::class, 'review', null, 16],
        'state' => [parent::class, 'state', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
