<?php

namespace DoctrineProxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Muser extends \Muser implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'houses' => [parent::class, 'houses', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'listOfOffers' => [parent::class, 'listOfOffers', null, 16],
        "\0".parent::class."\0".'meToReview' => [parent::class, 'meToReview', null, 16],
        "\0".parent::class."\0".'myPost' => [parent::class, 'myPost', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'profilePicture' => [parent::class, 'profilePicture', null, 16],
        "\0".parent::class."\0".'rating' => [parent::class, 'rating', null, 16],
        "\0".parent::class."\0".'report' => [parent::class, 'report', null, 16],
        "\0".parent::class."\0".'reviewToMe' => [parent::class, 'reviewToMe', null, 16],
        "\0".parent::class."\0".'surname' => [parent::class, 'surname', null, 16],
        "\0".parent::class."\0".'tel' => [parent::class, 'tel', null, 16],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null, 16],
        "\0".parent::class."\0".'verification' => [parent::class, 'verification', null, 16],
        "\0".parent::class."\0".'verified' => [parent::class, 'verified', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'houses' => [parent::class, 'houses', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'listOfOffers' => [parent::class, 'listOfOffers', null, 16],
        'meToReview' => [parent::class, 'meToReview', null, 16],
        'myPost' => [parent::class, 'myPost', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'profilePicture' => [parent::class, 'profilePicture', null, 16],
        'rating' => [parent::class, 'rating', null, 16],
        'report' => [parent::class, 'report', null, 16],
        'reviewToMe' => [parent::class, 'reviewToMe', null, 16],
        'surname' => [parent::class, 'surname', null, 16],
        'tel' => [parent::class, 'tel', null, 16],
        'username' => [parent::class, 'username', null, 16],
        'verification' => [parent::class, 'verification', null, 16],
        'verified' => [parent::class, 'verified', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
